version: '3.8'

services:
  pgvectordb:
    image: ankane/pgvector
    container_name: pgvectordb
    environment:
      POSTGRES_USER: pgvector
      POSTGRES_PASSWORD: pgvector
      POSTGRES_DB: pgvector
    volumes:
      - pgvectordata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fastapi_service:
    restart: always
    build:
      dockerfile: ./service.Dockerfile
    ports:
      - 8000:80
    depends_on:
      - pgvectordb
    env_file: .env

  prefect_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    volumes:
      - prefectdb:/var/lib/postgresql/data

  prefect_server:
    # copypasted from https://github.com/rpeden/prefect-docker-compose/ !
    image: prefecthq/prefect:2-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      # If you want to access Prefect Server UI from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL and PREFECT_API_URL to match the external hostname/IP of the host machine. For example:
      #- PREFECT_UI_URL=http://external-ip:4200/api
      #- PREFECT_API_URL=http://external-ip:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect_db:5432/prefect
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - 4200:4200
    depends_on:
      - prefect_db

volumes:
  pgvectordata:
  prefect:
  prefectdb:
networks:
  default:
    name: stateful-ml-network
