services:
  fastapi_service:
    restart: always
    build:
      dockerfile: ./service.Dockerfile
    ports:
      - 8000:80
    env_file: .env

  prefect_worker:
    build:
      dockerfile: ./worker.Dockerfile
    restart: always
    env_file: .env
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
