services:
  fastapi-service:
    restart: always
    build:
      context: ./workspace
      dockerfile: service/Dockerfile
    ports:
      - 8000:80
    env_file: .env

  terminal:
    build:
      context: .
      dockerfile: terminal.Dockerfile
