apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: prefect-worker
  name: prefect-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prefect-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/stateful-ml-network: "true"
        io.kompose.service: prefect-worker
    spec:
      containers:
        - command:
            - /opt/prefect/entrypoint.sh
            - prefect
            - worker
            - start
            - --type
            - docker
            - --pool
            - docker-pool
          env:
            - name: CODE_VERSION
              valueFrom:
                configMapKeyRef:
                  key: CODE_VERSION
                  name: env
            - name: CONTENT_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: CONTENT_BUCKET
                  name: env
            - name: MODEL_VERSION
              valueFrom:
                configMapKeyRef:
                  key: MODEL_VERSION
                  name: env
            - name: PREFECT_API_URL
              value: http://prefect-server:4200/api
            - name: PREFECT_DEFAULT_WORK_POOL_NAME
              valueFrom:
                configMapKeyRef:
                  key: PREFECT_DEFAULT_WORK_POOL_NAME
                  name: env
            - name: SUPABASE_KEY
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_KEY
                  name: env
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_URL
                  name: env
            - name: VECTORSTORE_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  key: VECTORSTORE_CONNECTION_STRING
                  name: env
          image: prefect-worker
          name: prefect-worker
          imagePullPolicy: Never
      restartPolicy: Always
