apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: prefect-db
  name: prefect-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
