name: Call deployment manager
on:
    push:
        tags:
            - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Environment
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == v*-rc* ]]; then
            echo "environment=stg" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == v* ]]; then
            echo "environment=prd" >> $GITHUB_OUTPUT
          else
            echo "tag not recognized" >&2
            exit 1
          fi

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.STATEFUL_ML_PAT }}
          repository: stateful-ml/deployment-manager
          event-type: code_update
          client-payload: '{"environment": "${{ steps.set-env.outputs.environment }}", "key": "tag", "value": "${{ github.ref_name }}"}'
